all:*.cpp
	g++ -O3 -Wall CochlearModel_1D_fft.cpp -o CochlearModel_1D_fft -I /usr/local/OpenBLAS/include/openblas -L/usr/local/OpenBLAS/lib -lopenblas -lpthread -llapack -lfftw3_threads -lfftw3 --std=c++11
